PLANET_HOUSE_INTERPRETATIONS = {
    # SOL NAS CASAS
    "sun_house_1": "A vitalidade se manifesta diretamente na forma de se apresentar ao mundo, através da postura, identidade e iniciativa pessoal. O cotidiano tende a girar em torno de afirmar quem se é e de iniciar movimentos que expressem autenticidade.",
    "sun_house_2": "A energia solar aparece nas decisões ligadas a dinheiro, valores e senso de segurança material. O dia a dia frequentemente envolve buscar reconhecimento através daquilo que se constrói, ganha ou sustenta.",
    "sun_house_3": "A vitalidade se expressa em conversas, trocas mentais e circulação de ideias no ambiente próximo. O cotidiano se alimenta de aprender, ensinar e comunicar aquilo que dá sentido à própria identidade.",
    "sun_house_4": "A energia do Sol se manifesta na vida doméstica, nas raízes e nas emoções ligadas à família. No cotidiano há um impulso de organizar o espaço íntimo e encontrar um centro emocional de pertencimento.",
    "sun_house_5": "A vitalidade aparece em atividades criativas, prazeres e expressões espontâneas de individualidade. O cotidiano tende a incluir momentos de criação, diversão ou demonstração calorosa de quem se é.",
    "sun_house_6": "A energia solar se manifesta no trabalho diário, nos hábitos e na forma de cuidar da saúde. O cotidiano envolve aperfeiçoar rotinas e encontrar sentido pessoal nas pequenas tarefas.",
    "sun_house_7": "A vitalidade se expressa nas relações e nos encontros significativos com o outro. O cotidiano frequentemente envolve negociar, cooperar e descobrir partes de si através das parcerias.",
    "sun_house_8": "A energia solar se manifesta em processos intensos de transformação emocional e psicológica. O cotidiano pode trazer situações que pedem profundidade, coragem e capacidade de renascer após crises.",
    "sun_house_9": "A vitalidade aparece na busca por sentido, conhecimento e expansão de horizontes. O cotidiano envolve estudar, refletir sobre crenças ou explorar novas perspectivas sobre a vida.",
    "sun_house_10": "A energia do Sol se manifesta nas ambições, carreira e imagem pública. O cotidiano tende a girar em torno de construir autoridade e deixar uma marca visível no mundo.",
    "sun_house_11": "A vitalidade se expressa em projetos coletivos, amizades e causas que apontam para o futuro. O cotidiano envolve colaborar com grupos e imaginar caminhos novos para a vida.",
    "sun_house_12": "A energia solar se manifesta em processos internos, silêncio e introspecção psicológica. O cotidiano pede momentos de recolhimento para compreender motivações profundas e integrar partes invisíveis de si.",

    # LUA NAS CASAS
    "moon_house_1": "As emoções aparecem diretamente na forma de reagir ao ambiente e às pessoas. O cotidiano é marcado por oscilações de humor que influenciam a forma de agir e se posicionar.",
    "moon_house_2": "A vida emocional se conecta fortemente à sensação de segurança material e estabilidade. No cotidiano há uma busca constante por conforto, estabilidade e proteção dos próprios recursos.",
    "moon_house_3": "Os sentimentos se manifestam através da fala, da escrita e das conversas próximas. O cotidiano envolve compartilhar emoções e interpretar o mundo através de diálogos e trocas mentais.",
    "moon_house_4": "A sensibilidade se expressa intensamente no ambiente doméstico e familiar. O cotidiano gira em torno de cuidar, proteger e buscar abrigo emocional no próprio espaço íntimo.",
    "moon_house_5": "As emoções se manifestam em gestos criativos, romances e expressões afetivas espontâneas. O cotidiano inclui momentos de prazer emocional ao criar, brincar ou demonstrar carinho.",
    "moon_house_6": "A vida emocional aparece nos hábitos, no cuidado com o corpo e nas tarefas diárias. O cotidiano pode envolver oscilações no ritmo de trabalho conforme o estado emocional.",
    "moon_house_7": "Os sentimentos se tornam mais claros nas relações e nas interações íntimas. O cotidiano envolve responder emocionalmente às necessidades e reações das pessoas próximas.",
    "moon_house_8": "A sensibilidade se manifesta em emoções profundas, intensas e transformadoras. O cotidiano pode trazer confrontos com medos, intimidade e processos psicológicos profundos.",
    "moon_house_9": "Os sentimentos se expandem através de ideias, crenças e reflexões sobre a vida. O cotidiano envolve buscar sentido emocional em filosofias, estudos ou experiências novas.",
    "moon_house_10": "A vida emocional se manifesta na relação com reconhecimento público e realização profissional. O cotidiano pode oscilar conforme a sensação de aprovação ou exposição social.",
    "moon_house_11": "Os sentimentos se conectam com amizades e com o sentimento de pertencimento a grupos. O cotidiano envolve trocar apoio emocional dentro de redes sociais ou coletivas.",
    "moon_house_12": "A sensibilidade se move em camadas internas e muitas vezes silenciosas da psique. O cotidiano pode incluir períodos de introspecção profunda e necessidade de solitude emocional.",

    # MERCÚRIO NAS CASAS
    "mercury_house_1": "A mente se manifesta diretamente na forma de falar, se apresentar e reagir ao ambiente. O cotidiano é marcado por curiosidade, perguntas e comunicação constante.",
    "mercury_house_2": "O pensamento se volta para decisões práticas ligadas a dinheiro e segurança. O cotidiano envolve calcular, planejar e refletir sobre recursos e valores pessoais.",
    "mercury_house_3": "A energia mental encontra seu território natural na troca de ideias e na comunicação cotidiana. O dia a dia se preenche com conversas, aprendizado rápido e circulação de informações.",
    "mercury_house_4": "Os pensamentos frequentemente giram em torno da história pessoal e das raízes familiares. O cotidiano inclui reflexões sobre memórias, pertencimento e dinâmica doméstica.",
    "mercury_house_5": "A mente se manifesta de forma criativa e expressiva. O cotidiano envolve escrever, criar, contar histórias ou brincar com ideias de maneira espontânea.",
    "mercury_house_6": "O pensamento se organiza em torno de tarefas, planejamento e eficiência. O cotidiano envolve analisar problemas práticos e otimizar rotinas.",
    "mercury_house_7": "A mente ganha clareza através do diálogo e da troca com outras pessoas. O cotidiano envolve negociar, argumentar e compreender diferentes pontos de vista.",
    "mercury_house_8": "Os pensamentos mergulham em temas psicológicos, mistérios e assuntos profundos. O cotidiano envolve investigar motivações ocultas e compreender dinâmicas emocionais complexas.",
    "mercury_house_9": "A mente busca ampliar horizontes através de estudo, filosofia ou viagens mentais. O cotidiano envolve questionar crenças e explorar novas formas de compreender a realidade.",
    "mercury_house_10": "O pensamento se manifesta em decisões estratégicas ligadas à carreira e à imagem pública. O cotidiano envolve planejar metas e comunicar ideias em ambientes profissionais.",
    "mercury_house_11": "A mente se ativa em conversas com grupos, projetos coletivos e ideias inovadoras. O cotidiano envolve colaborar mentalmente com pessoas que compartilham interesses.",
    "mercury_house_12": "Os pensamentos se movem em processos internos e reflexivos. O cotidiano inclui momentos de introspecção, imaginação e elaboração silenciosa de ideias.",

    # VÊNUS NAS CASAS
    "venus_house_1": "O afeto se manifesta na maneira de se apresentar e se relacionar com o mundo. O cotidiano envolve buscar harmonia nas interações e cuidar da própria imagem.",
    "venus_house_2": "O prazer se conecta com segurança material e conforto sensorial. O cotidiano inclui valorizar aquilo que traz estabilidade e bem-estar concreto.",
    "venus_house_3": "O afeto se expressa através da comunicação e das trocas leves com o ambiente próximo. O cotidiano envolve conversas agradáveis, humor e troca de ideias afetuosas.",
    "venus_house_4": "O amor se manifesta na vida doméstica e no cuidado com o lar. O cotidiano inclui criar um ambiente emocionalmente acolhedor.",
    "venus_house_5": "O afeto aparece em gestos criativos, romances e prazer espontâneo. O cotidiano envolve expressar carinho através de arte, diversão ou sedução.",
    "venus_house_6": "O prazer se manifesta na organização da vida diária e no cuidado com o corpo. O cotidiano envolve buscar equilíbrio e estética nas rotinas.",
    "venus_house_7": "O amor se expressa diretamente nas relações e parcerias. O cotidiano envolve cultivar harmonia e cooperação nos vínculos.",
    "venus_house_8": "O afeto se move em territórios intensos de intimidade e transformação emocional. O cotidiano envolve vínculos profundos e trocas emocionais intensas.",
    "venus_house_9": "O prazer se manifesta ao explorar ideias, culturas ou experiências que ampliam horizontes. O cotidiano envolve curiosidade afetiva pelo mundo.",
    "venus_house_10": "O afeto se conecta com reconhecimento social e imagem pública. O cotidiano pode envolver relações e estética ligadas ao ambiente profissional.",
    "venus_house_11": "O amor aparece nas amizades e nos projetos coletivos. O cotidiano envolve compartilhar afinidades e interesses em grupo.",
    "venus_house_12": "O afeto se move em dimensões internas e muitas vezes silenciosas da psique. O cotidiano pode envolver sentimentos discretos ou processos afetivos introspectivos.",

    # MARTE NAS CASAS
    "mars_house_1": "A energia de ação se manifesta diretamente na postura e iniciativa pessoal. O cotidiano envolve agir rapidamente diante dos desafios.",
    "mars_house_2": "A força de ação se direciona para construir segurança material. O cotidiano envolve lutar por recursos e autonomia financeira.",
    "mars_house_3": "A energia se manifesta em debates, decisões rápidas e comunicação direta. O cotidiano envolve defender ideias e agir através da palavra.",
    "mars_house_4": "A ação se direciona para questões familiares e domésticas. O cotidiano pode envolver proteger o território emocional ou resolver conflitos no lar.",
    "mars_house_5": "A energia aparece em criatividade, paixão e iniciativas espontâneas. O cotidiano envolve agir impulsivamente em busca de prazer ou expressão pessoal.",
    "mars_house_6": "A força de ação se manifesta nas rotinas e no trabalho diário. O cotidiano envolve resolver problemas práticos com energia e eficiência.",
    "mars_house_7": "A energia se manifesta nos encontros e confrontos com outras pessoas. O cotidiano envolve negociar conflitos e afirmar vontades nas relações.",
    "mars_house_8": "A ação ocorre em processos intensos de transformação emocional. O cotidiano envolve enfrentar crises ou desafios psicológicos profundos.",
    "mars_house_9": "A energia se dirige para explorar ideias e horizontes novos. O cotidiano envolve defender crenças e buscar experiências que expandem a mente.",
    "mars_house_10": "A ação se manifesta na ambição e na busca por reconhecimento público. O cotidiano envolve lutar por objetivos profissionais.",
    "mars_house_11": "A energia se move em projetos coletivos e iniciativas de grupo. O cotidiano envolve agir em direção a objetivos compartilhados.",
    "mars_house_12": "A força de ação opera em níveis internos e inconscientes. O cotidiano pode envolver conflitos internos ou energia direcionada a processos psicológicos profundos.",

    # JÚPITER NAS CASAS
    "jupiter_house_1": "A expansão se manifesta na forma de se posicionar e agir no mundo. O cotidiano envolve experimentar a vida com entusiasmo e confiança.",
    "jupiter_house_2": "O crescimento aparece na construção de segurança material e valores pessoais. O cotidiano envolve buscar oportunidades financeiras e estabilidade.",
    "jupiter_house_3": "A expansão se manifesta na curiosidade mental e nas trocas de conhecimento. O cotidiano envolve aprender, ensinar e circular ideias.",
    "jupiter_house_4": "O crescimento ocorre através da vida familiar e do desenvolvimento emocional. O cotidiano envolve construir um senso mais amplo de pertencimento.",
    "jupiter_house_5": "A expansão aparece na criatividade, no prazer e nas expressões espontâneas. O cotidiano envolve explorar talentos e momentos de alegria.",
    "jupiter_house_6": "O crescimento se manifesta na melhoria das rotinas e hábitos. O cotidiano envolve aperfeiçoar o trabalho e cuidar do corpo.",
    "jupiter_house_7": "A expansão se dá através das relações e parcerias significativas. O cotidiano envolve aprender com o outro e crescer em cooperação.",
    "jupiter_house_8": "O crescimento acontece em processos profundos de transformação emocional. O cotidiano envolve explorar dimensões psicológicas intensas.",
    "jupiter_house_9": "A expansão se manifesta na busca por conhecimento, viagens e filosofia. O cotidiano envolve explorar ideias que ampliam a visão de mundo.",
    "jupiter_house_10": "O crescimento aparece na carreira e no reconhecimento público. O cotidiano envolve buscar oportunidades de liderança e expansão profissional.",
    "jupiter_house_11": "A expansão se manifesta em amizades e projetos coletivos. O cotidiano envolve participar de redes que ampliam horizontes.",
    "jupiter_house_12": "O crescimento ocorre em processos internos e espirituais. O cotidiano envolve momentos de introspecção e compreensão profunda da vida.",

    # SATURNO NAS CASAS
    "saturn_house_1": "A disciplina se manifesta na construção da própria identidade e postura diante do mundo. O cotidiano envolve desenvolver responsabilidade pessoal e maturidade.",
    "saturn_house_2": "A energia saturnina aparece na relação com dinheiro e segurança material. O cotidiano envolve administrar recursos com cautela e planejamento.",
    "saturn_house_3": "A disciplina se manifesta na comunicação e no pensamento estruturado. O cotidiano envolve organizar ideias e assumir responsabilidade pelas palavras.",
    "saturn_house_4": "A maturidade se desenvolve através das experiências familiares e emocionais. O cotidiano envolve lidar com responsabilidades domésticas e raízes profundas.",
    "saturn_house_5": "A disciplina aparece na expressão criativa e nos prazeres da vida. O cotidiano envolve aprender a expressar autenticidade com responsabilidade.",
    "saturn_house_6": "A energia se manifesta na organização do trabalho e das rotinas. O cotidiano envolve esforço constante para manter ordem e eficiência.",
    "saturn_house_7": "A maturidade se desenvolve nas relações e compromissos com outras pessoas. O cotidiano envolve aprender sobre limites e responsabilidades nos vínculos.",
    "saturn_house_8": "A disciplina aparece em processos intensos de transformação psicológica. O cotidiano envolve enfrentar medos profundos e desenvolver resiliência emocional.",
    "saturn_house_9": "A maturidade se constrói através de crenças, estudos e visão de mundo. O cotidiano envolve questionar ideias e desenvolver convicções sólidas.",
    "saturn_house_10": "A disciplina se manifesta fortemente na carreira e nas ambições. O cotidiano envolve trabalhar com persistência para construir reconhecimento.",
    "saturn_house_11": "A maturidade aparece na participação em grupos e projetos coletivos. O cotidiano envolve assumir responsabilidades dentro de comunidades.",
    "saturn_house_12": "A disciplina se desenvolve em processos internos e silenciosos da psique. O cotidiano envolve enfrentar limites internos e cultivar introspecção.",

    # URANO NAS CASAS
    "uranus_house_1": "A energia de mudança se manifesta diretamente na forma de agir e se apresentar. O cotidiano envolve impulsos de liberdade e atitudes inesperadas.",
    "uranus_house_2": "A inovação aparece na maneira de lidar com dinheiro e valores pessoais. O cotidiano envolve buscar caminhos diferentes para construir segurança.",
    "uranus_house_3": "A mente se move de forma rápida, criativa e original. O cotidiano envolve ideias inesperadas e comunicação fora do padrão.",
    "uranus_house_4": "Mudanças surgem no ambiente familiar e nas bases emocionais. O cotidiano pode incluir transformações inesperadas na vida doméstica.",
    "uranus_house_5": "A criatividade se manifesta de forma livre e inovadora. O cotidiano envolve experimentar novas formas de expressão pessoal.",
    "uranus_house_6": "A mudança aparece nas rotinas e no trabalho diário. O cotidiano envolve quebrar padrões e experimentar métodos diferentes.",
    "uranus_house_7": "A energia de liberdade se manifesta nas relações. O cotidiano envolve encontros inesperados ou vínculos pouco convencionais.",
    "uranus_house_8": "A transformação ocorre em níveis profundos da psique. O cotidiano envolve insights repentinos sobre emoções e dinâmicas psicológicas.",
    "uranus_house_9": "A inovação aparece na forma de pensar e compreender o mundo. O cotidiano envolve explorar ideias radicais ou novas filosofias.",
    "uranus_house_10": "Mudanças inesperadas podem ocorrer na carreira e na imagem pública. O cotidiano envolve reinventar objetivos profissionais.",
    "uranus_house_11": "A energia se manifesta em projetos coletivos e redes sociais. O cotidiano envolve colaborar com grupos inovadores.",
    "uranus_house_12": "A mudança ocorre em camadas profundas e inconscientes da psique. O cotidiano envolve insights repentinos sobre processos internos.",

    # NETUNO NAS CASAS
    "neptune_house_1": "A sensibilidade se manifesta na forma de perceber e reagir ao mundo. O cotidiano envolve captar atmosferas emocionais e energias sutis.",
    "neptune_house_2": "A imaginação se conecta com valores e segurança material. O cotidiano envolve oscilar entre idealismo e realidade nas decisões financeiras.",
    "neptune_house_3": "A mente se move através de imaginação, símbolos e sensibilidade intuitiva. O cotidiano envolve interpretar o mundo através de percepções subjetivas.",
    "neptune_house_4": "A sensibilidade se manifesta no ambiente familiar e emocional. O cotidiano envolve buscar um lar que ofereça sensação de refúgio psicológico.",
    "neptune_house_5": "A imaginação se expressa em criatividade, arte e romance. O cotidiano envolve momentos de inspiração e idealização afetiva.",
    "neptune_house_6": "A sensibilidade aparece nas rotinas e na relação com o corpo. O cotidiano envolve necessidade de equilíbrio entre sensibilidade e organização.",
    "neptune_house_7": "A imaginação se manifesta nas relações e na forma de perceber o outro. O cotidiano envolve idealizar ou projetar expectativas nos vínculos.",
    "neptune_house_8": "A sensibilidade se move em territórios emocionais profundos. O cotidiano envolve experiências psicológicas intensas e transformadoras.",
    "neptune_house_9": "A imaginação se manifesta em crenças, espiritualidade e visão de mundo. O cotidiano envolve buscar significado simbólico nas experiências.",
    "neptune_house_10": "A sensibilidade aparece na imagem pública e nos objetivos profissionais. O cotidiano envolve buscar um propósito que transcenda ambições materiais.",
    "neptune_house_11": "A imaginação se manifesta em sonhos coletivos e ideais sociais. O cotidiano envolve conectar-se com grupos através de ideais compartilhados.",
    "neptune_house_12": "A sensibilidade se move em níveis profundos da psique e da espiritualidade. O cotidiano envolve introspecção, sonhos e processos inconscientes.",

    # PLUTÃO NAS CASAS
    "pluto_house_1": "A energia de transformação se manifesta diretamente na forma de existir e agir. O cotidiano envolve processos intensos de mudança pessoal.",
    "pluto_house_2": "A transformação ocorre na relação com dinheiro, valores e segurança. O cotidiano envolve confrontar padrões profundos ligados a poder material.",
    "pluto_house_3": "A mente se move em investigações profundas e conversas intensas. O cotidiano envolve buscar a verdade por trás das palavras.",
    "pluto_house_4": "A transformação ocorre nas raízes emocionais e familiares. O cotidiano envolve confrontar padrões herdados e reconstruir o senso de pertencimento.",
    "pluto_house_5": "A intensidade aparece na criatividade, nos romances e na autoexpressão. O cotidiano envolve experiências emocionais profundas ligadas ao prazer.",
    "pluto_house_6": "A transformação se manifesta nas rotinas e no trabalho diário. O cotidiano envolve reformular hábitos e enfrentar padrões de controle.",
    "pluto_house_7": "A intensidade se revela nas relações e parcerias. O cotidiano envolve encontros que provocam mudanças psicológicas profundas.",
    "pluto_house_8": "A energia plutoniana encontra seu território natural em processos de morte e renascimento psicológico. O cotidiano envolve enfrentar emoções profundas e transformadoras.",
    "pluto_house_9": "A transformação ocorre nas crenças e na visão de mundo. O cotidiano envolve questionar ideias antigas e reconstruir significados.",
    "pluto_house_10": "A intensidade aparece na carreira e na busca por poder ou influência. O cotidiano envolve enfrentar desafios ligados à autoridade.",
    "pluto_house_11": "A transformação se manifesta em grupos, amizades e projetos coletivos. O cotidiano envolve reformular alianças e objetivos sociais.",
    "pluto_house_12": "A energia de transformação opera nas camadas mais profundas da psique. O cotidiano envolve confrontar conteúdos inconscientes e integrar sombras.",
}
