PLANET_SIGN_INTERPRETATIONS = {
    # SOL
    "sun_aries": "O Sol em Áries pulsa como um impulso de nascimento constante, onde a identidade se afirma através da coragem de iniciar e confrontar o desconhecido. Há uma chama interna que se fortalece no ato de agir, como se a existência ganhasse sentido apenas quando algo novo é colocado em movimento.",
    "sun_taurus": "O Sol em Touro busca consolidar a identidade através da permanência, da matéria e daquilo que pode ser sentido com o corpo. A vitalidade floresce quando o tempo desacelera e a experiência se transforma em algo concreto, estável e profundamente enraizado.",
    "sun_gemini": "O Sol em Gêmeos encontra sua expressão no movimento da mente e na multiplicidade de perspectivas que constroem a consciência. A identidade se ilumina quando o pensamento circula, conecta e transforma o mundo em linguagem e curiosidade viva.",
    "sun_cancer": "O Sol em Câncer se orienta pelo instinto de proteger e nutrir aquilo que guarda valor emocional profundo. A identidade se fortalece quando existe um território íntimo onde a memória, o cuidado e o pertencimento podem respirar.",
    "sun_leo": "O Sol em Leão se manifesta como um centro criativo que busca irradiar presença e significado no mundo. Há um impulso de viver como obra viva, onde a autenticidade e a expressão do coração tornam-se a fonte da vitalidade.",
    "sun_virgo": "O Sol em Virgem ilumina a identidade através da atenção minuciosa aos detalhes que sustentam a ordem da vida. Existe uma busca interna por aperfeiçoamento e utilidade, como se o sentido de existir estivesse em refinar aquilo que ainda pode ser melhorado.",
    "sun_libra": "O Sol em Libra se revela no encontro entre o eu e o outro, onde a identidade se constrói através da troca e da harmonia relacional. A consciência busca equilíbrio, percebendo que a beleza e a justiça surgem quando diferentes forças encontram proporção.",
    "sun_scorpio": "O Sol em Escorpião carrega a força da transformação psíquica, onde a identidade nasce das crises e renascimentos internos. Há uma intensidade que convida a mergulhar nas profundezas da experiência para revelar verdades ocultas.",
    "sun_sagittarius": "O Sol em Sagitário expande a identidade através da busca por significado, visão e horizonte. A vitalidade cresce quando a vida se torna uma jornada de descoberta filosófica e liberdade interior.",
    "sun_capricorn": "O Sol em Capricórnio constrói sua identidade a partir da responsabilidade diante do tempo e da realidade. Existe uma força silenciosa que encontra sentido ao transformar esforço em estrutura e propósito duradouro.",
    "sun_aquarius": "O Sol em Aquário se expressa como consciência voltada para o coletivo e para o futuro. A identidade se ilumina quando há liberdade para questionar padrões e imaginar novas formas de organização humana.",
    "sun_pisces": "O Sol em Peixes dissolve as fronteiras rígidas da identidade, conectando o indivíduo a dimensões sensíveis e simbólicas da existência. A vitalidade emerge quando a vida é vivida como experiência de compaixão, imaginação e transcendência.",

    # LUA
    "moon_aries": "A Lua em Áries reage ao mundo emocional através do impulso imediato e da necessidade de afirmar sua vontade. Os sentimentos surgem como fogo que pede movimento, tornando difícil permanecer em estados emocionais passivos.",
    "moon_taurus": "A Lua em Touro busca segurança emocional através da estabilidade e da continuidade das sensações familiares. O afeto se aprofunda quando existe ritmo, previsibilidade e um território emocional que não muda abruptamente.",
    "moon_gemini": "A Lua em Gêmeos processa emoções através da linguagem e da compreensão mental das experiências. O mundo afetivo se organiza quando sentimentos podem ser pensados, compartilhados e transformados em diálogo.",
    "moon_cancer": "A Lua em Câncer encontra segurança emocional na intimidade e na proteção do vínculo. As emoções funcionam como marés profundas que conectam o presente às memórias e às raízes afetivas.",
    "moon_leo": "A Lua em Leão vive o afeto como expressão calorosa que deseja ser reconhecida e acolhida. Existe uma necessidade emocional de criar, oferecer e sentir que o coração tem espaço para brilhar.",
    "moon_virgo": "A Lua em Virgem organiza o mundo emocional através da observação e do cuidado com os detalhes da vida cotidiana. Os sentimentos encontram equilíbrio quando podem ser úteis, compreendidos e colocados em ordem.",
    "moon_libra": "A Lua em Libra busca estabilidade emocional na harmonia das relações e na sensação de reciprocidade. O afeto floresce quando existe beleza, diálogo e equilíbrio entre dar e receber.",
    "moon_scorpio": "A Lua em Escorpião sente de forma intensa e profunda, como se cada emoção carregasse um potencial de transformação psíquica. Existe um magnetismo emocional que conduz a confrontar medos, perdas e renascimentos internos.",
    "moon_sagittarius": "A Lua em Sagitário encontra segurança emocional na expansão da experiência e na liberdade de explorar o mundo. O afeto se renova quando existe espaço para crescer, aprender e respirar horizontes amplos.",
    "moon_capricorn": "A Lua em Capricórnio regula o mundo emocional através da contenção e da responsabilidade afetiva. Existe uma necessidade de construir segurança interna com base em maturidade e estabilidade concreta.",
    "moon_aquarius": "A Lua em Aquário processa emoções através da distância reflexiva e da percepção de padrões coletivos. O afeto encontra equilíbrio quando há liberdade para sentir sem aprisionamento emocional.",
    "moon_pisces": "A Lua em Peixes absorve emoções como um oceano sensível que percebe nuances invisíveis no ambiente. O mundo afetivo se move entre imaginação, empatia profunda e uma sensação de conexão com algo maior.",

    # MERCÚRIO
    "mercury_aries": "Mercúrio em Áries pensa como um impulso direto que transforma ideias em ação rápida. A mente funciona como centelha que prefere iniciar debates e caminhos novos a permanecer em reflexões prolongadas.",
    "mercury_taurus": "Mercúrio em Touro organiza o pensamento de forma lenta e consistente, buscando ideias que possam se sustentar no tempo. A mente valoriza aquilo que é concreto, confiável e construído com paciência.",
    "mercury_gemini": "Mercúrio em Gêmeos se move como rede viva de informações que conecta conceitos, palavras e possibilidades. O pensamento encontra vitalidade na troca constante e na curiosidade que transforma tudo em pergunta.",
    "mercury_cancer": "Mercúrio em Câncer pensa a partir da memória emocional e da sensibilidade ao clima afetivo ao redor. A comunicação carrega nuances subjetivas, como se cada palavra fosse atravessada por lembranças e sentimentos.",
    "mercury_leo": "Mercúrio em Leão expressa ideias com intensidade criativa e desejo de impacto. A mente se ilumina quando pode comunicar com autenticidade, dramatização e presença marcante.",
    "mercury_virgo": "Mercúrio em Virgem analisa o mundo com precisão e senso crítico refinado. O pensamento busca compreender sistemas, corrigir falhas e organizar a realidade em estruturas coerentes.",
    "mercury_libra": "Mercúrio em Libra pensa através da comparação e da busca por equilíbrio entre diferentes pontos de vista. A mente se movimenta como diplomata interno que tenta encontrar harmonia entre argumentos opostos.",
    "mercury_scorpio": "Mercúrio em Escorpião investiga o pensamento como quem atravessa camadas ocultas da realidade. Existe uma mente penetrante que busca revelar aquilo que permanece escondido sob a superfície.",
    "mercury_sagittarius": "Mercúrio em Sagitário pensa em grande escala, conectando ideias a visões amplas de sentido. O pensamento prefere explorar conceitos, filosofias e narrativas que expandem a compreensão do mundo.",
    "mercury_capricorn": "Mercúrio em Capricórnio organiza o pensamento com disciplina e orientação para resultados concretos. A mente valoriza estratégias, planejamento e ideias que possam se transformar em estrutura prática.",
    "mercury_aquarius": "Mercúrio em Aquário opera através de insights originais e pensamento não convencional. A mente observa sistemas sociais e conceituais como quem busca padrões inéditos e possibilidades futuras.",
    "mercury_pisces": "Mercúrio em Peixes pensa de forma simbólica, intuitiva e sensível às dimensões invisíveis da experiência. As ideias surgem como imagens e percepções sutis que escapam da lógica linear.",

    # VÊNUS
    "venus_aries": "O desejo afetivo emerge como impulso direto e apaixonado, buscando intensidade mais do que segurança. O amor funciona como território de conquista, onde o entusiasmo inicial frequentemente vale mais do que a permanência.",
    "venus_taurus": "O vínculo afetivo se constrói através da estabilidade, do toque e da experiência sensorial compartilhada. O prazer nasce da continuidade e da segurança, transformando o amor em algo que precisa ser cultivado e preservado.",
    "venus_gemini": "O afeto se manifesta através da curiosidade, da conversa e da troca intelectual constante. A atração cresce quando há movimento mental e leveza, como se o amor precisasse permanecer vivo através do diálogo.",
    "venus_cancer": "O amor busca intimidade emocional profunda e um sentimento de pertencimento quase familiar. O vínculo se fortalece quando existe cuidado, proteção e a sensação de poder baixar as defesas.",
    "venus_leo": "O afeto deseja ser vivido com brilho, reconhecimento e expressão generosa do coração. Amar torna-se um ato criativo, onde a troca emocional precisa também alimentar o sentimento de admiração mútua.",
    "venus_virgo": "O amor se manifesta através da atenção aos detalhes e do desejo de cuidar do cotidiano do outro. A expressão afetiva surge mais em gestos concretos de apoio do que em grandes declarações emocionais.",
    "venus_libra": "O vínculo afetivo procura harmonia, reciprocidade e estética nas relações. O amor se torna um espaço de equilíbrio onde a troca precisa ser justa e emocionalmente elegante.",
    "venus_scorpio": "O afeto mergulha em profundidade emocional, buscando intensidade e fusão psicológica. Amar envolve transformação, onde confiança e vulnerabilidade tornam-se territórios sagrados.",
    "venus_sagittarius": "O amor se associa à liberdade, ao crescimento e à descoberta de novos horizontes emocionais. O vínculo floresce quando a relação permite expansão e verdade.",
    "venus_capricorn": "O afeto se constrói lentamente através de compromisso, responsabilidade e confiabilidade. Amar significa investir em algo que possa resistir ao tempo e às dificuldades.",
    "venus_aquarius": "O amor nasce da afinidade mental e do respeito pela individualidade de cada um. O vínculo floresce quando existe liberdade para ser diferente e autêntico dentro da relação.",
    "venus_pisces": "O afeto se dissolve em empatia, sensibilidade e conexão emocional quase intuitiva. Amar torna-se uma experiência de transcendência, onde as fronteiras entre eu e outro podem se suavizar.",

    # MARTE
    "mars_aries": "A ação emerge como impulso imediato que busca enfrentar desafios de forma direta. A energia se move através da coragem de iniciar e da necessidade de afirmar a própria força.",
    "mars_taurus": "A ação se manifesta de maneira persistente e constante, avançando com firmeza em direção ao que deseja construir. A energia não corre, ela se acumula até se tornar impossível de deter.",
    "mars_gemini": "A iniciativa surge através da palavra, da curiosidade e da multiplicidade de ideias. A energia se expressa no movimento mental e na capacidade de explorar diferentes caminhos.",
    "mars_cancer": "A ação é guiada por emoções profundas e pela necessidade de proteger aquilo que é significativo. A energia muitas vezes se move de forma indireta, respondendo mais aos sentimentos do que à lógica.",
    "mars_leo": "A iniciativa se manifesta com força criativa e desejo de expressão pessoal. A energia busca palco, reconhecimento e a possibilidade de agir com autenticidade.",
    "mars_virgo": "A ação se organiza através da análise, da estratégia e da atenção aos detalhes. A energia se concentra em melhorar, corrigir e aperfeiçoar aquilo que toca.",
    "mars_libra": "A iniciativa surge através da negociação e da tentativa de equilibrar forças opostas. A ação procura harmonia, mesmo quando precisa lidar com conflitos.",
    "mars_scorpio": "A energia de ação mergulha em intensidade emocional e determinação profunda. A vontade se move com foco quase obsessivo quando algo desperta verdadeiro desejo.",
    "mars_sagittarius": "A ação se orienta pela busca de significado, aventura e expansão de horizontes. A energia avança quando existe um propósito maior que justifique o movimento.",
    "mars_capricorn": "A iniciativa se manifesta através de disciplina, estratégia e visão de longo prazo. A energia se concentra em construir resultados sólidos e duradouros.",
    "mars_aquarius": "A ação surge com impulso de inovação e desejo de romper padrões estabelecidos. A energia se direciona para mudanças que ampliem liberdade e novas possibilidades.",
    "mars_pisces": "A iniciativa se move de forma intuitiva e sensível aos ambientes emocionais ao redor. A energia muitas vezes flui mais como inspiração do que como confronto direto.",

    # JÚPITER
    "jupiter_aries": "O crescimento acontece através da coragem de iniciar novos caminhos e confiar na própria força. A expansão surge quando há espaço para agir com autenticidade e ousadia.",
    "jupiter_taurus": "A expansão se desenvolve através da construção gradual de estabilidade e abundância concreta. O crescimento floresce quando há paciência para cultivar aquilo que tem valor.",
    "jupiter_gemini": "O desenvolvimento acontece através da curiosidade intelectual e da troca constante de ideias. A expansão surge quando o conhecimento circula e novas perspectivas são exploradas.",
    "jupiter_cancer": "O crescimento se manifesta através do cuidado, da proteção e da construção de vínculos significativos. A expansão emocional acontece quando existe espaço para nutrir e ser nutrido.",
    "jupiter_leo": "A expansão acontece através da expressão criativa e da confiança no próprio brilho. O crescimento floresce quando o coração encontra espaço para se expressar com generosidade.",
    "jupiter_virgo": "O desenvolvimento se constrói através da melhoria contínua e da busca por utilidade concreta. A expansão acontece quando o conhecimento é aplicado para tornar a vida mais funcional.",
    "jupiter_libra": "O crescimento surge através das relações, das parcerias e do encontro com o outro. A expansão acontece quando a vida se organiza em torno de trocas equilibradas.",
    "jupiter_scorpio": "A expansão ocorre através da transformação profunda e da exploração das camadas ocultas da experiência. O crescimento surge quando há coragem de enfrentar a intensidade emocional.",
    "jupiter_sagittarius": "O desenvolvimento se manifesta através da busca por sentido, filosofia e exploração do mundo. A expansão floresce quando há liberdade para seguir aquilo que inspira.",
    "jupiter_capricorn": "O crescimento se constrói através de estrutura, responsabilidade e conquistas progressivas. A expansão acontece quando ambição encontra disciplina.",
    "jupiter_aquarius": "A expansão surge através de ideias inovadoras e da conexão com projetos coletivos. O crescimento acontece quando o pensamento se abre para o futuro.",
    "jupiter_pisces": "O desenvolvimento se manifesta através da compaixão, da imaginação e da sensibilidade espiritual. A expansão acontece quando há abertura para experiências que transcendem o controle racional.",

    # SATURNO
    "saturn_aries": "A força de agir encontra limites que exigem maturidade antes do impulso. A coragem se desenvolve quando a iniciativa aprende disciplina e responsabilidade.",
    "saturn_taurus": "A segurança material torna-se um campo de provas para paciência e constância. O valor das coisas é aprendido lentamente através de esforço e construção sólida.",
    "saturn_gemini": "A mente aprende que pensamento exige rigor e estrutura para ganhar consistência. A comunicação amadurece quando as palavras passam a carregar responsabilidade e precisão.",
    "saturn_cancer": "A sensibilidade emocional encontra desafios que pedem fortalecimento interno. O senso de proteção se constrói quando o cuidado deixa de ser medo e se torna estrutura afetiva.",
    "saturn_leo": "A expressão criativa passa por testes que exigem autenticidade e humildade. O brilho pessoal se consolida quando o ego aprende responsabilidade sobre aquilo que cria.",
    "saturn_virgo": "A busca por aperfeiçoamento transforma-se em um treinamento constante de discernimento. O serviço ganha profundidade quando a crítica se transforma em competência prática.",
    "saturn_libra": "Os vínculos revelam lições sobre equilíbrio, limites e compromisso. A harmonia verdadeira surge quando o encontro com o outro envolve responsabilidade emocional.",
    "saturn_scorpio": "As experiências intensas exigem confrontos com medo, controle e vulnerabilidade. A transformação ocorre quando o poder emocional é usado com consciência.",
    "saturn_sagittarius": "As crenças passam por provas que exigem coerência entre pensamento e realidade. A sabedoria surge quando o entusiasmo filosófico encontra responsabilidade intelectual.",
    "saturn_capricorn": "A ambição encontra seu campo natural de disciplina, estratégia e perseverança. O poder se constrói lentamente através de responsabilidade e maturidade estrutural.",
    "saturn_aquarius": "A liberdade intelectual precisa aprender a coexistir com responsabilidade coletiva. A inovação se fortalece quando a visão do futuro encontra compromisso social.",
    "saturn_pisces": "A sensibilidade psíquica exige limites para não se perder em confusão emocional. A compaixão amadurece quando a empatia se apoia em estrutura interna.",

    # URANO
    "uranus_aries": "A necessidade de autonomia surge como impulso de ruptura e afirmação radical do eu. A identidade busca liberdade através de ações inesperadas e pioneiras.",
    "uranus_taurus": "Mudanças profundas atravessam valores, recursos e segurança material. A estabilidade é questionada para abrir espaço a novas formas de relação com o mundo físico.",
    "uranus_gemini": "A mente torna-se campo de experimentação e ideias disruptivas. O pensamento rompe padrões antigos para abrir caminhos de comunicação inovadora.",
    "uranus_cancer": "A experiência emocional e familiar passa por mudanças inesperadas. O sentimento de pertencimento busca novas formas de cuidado e intimidade.",
    "uranus_leo": "A criatividade emerge como expressão singular e imprevisível. O desejo de brilhar rompe convenções e redefine o significado de autenticidade.",
    "uranus_virgo": "A organização da vida cotidiana é transformada por novas formas de eficiência. O trabalho e os hábitos se reinventam através de soluções experimentais.",
    "uranus_libra": "As relações tornam-se território de inovação e redefinição de vínculos. A liberdade no encontro com o outro desafia modelos tradicionais de parceria.",
    "uranus_scorpio": "Mudanças abruptas atravessam temas de poder, intimidade e transformação. A psique mergulha em processos intensos que libertam energias profundas.",
    "uranus_sagittarius": "A visão de mundo expande-se através de rupturas filosóficas e culturais. A busca por verdade desafia dogmas e abre novas fronteiras de pensamento.",
    "uranus_capricorn": "Estruturas sociais e profissionais passam por reinvenções radicais. A autoridade é questionada para criar novos modelos de organização e liderança.",
    "uranus_aquarius": "A liberdade coletiva torna-se motor de revoluções sociais e tecnológicas. O pensamento progressista busca redes, inovação e novos paradigmas de convivência.",
    "uranus_pisces": "A imaginação abre portais inesperados entre realidade e dimensão simbólica. A sensibilidade psíquica experimenta novas formas de conexão espiritual.",

    # NETUNO
    "neptune_aries": "O impulso de agir é atravessado por sonhos e visões idealizadas de identidade. A coragem pode ser guiada por inspiração ou dissolver-se em ilusões heroicas.",
    "neptune_taurus": "Os valores materiais tornam-se permeáveis a idealizações e fantasias. O desejo de segurança busca significado em experiências sensoriais e estéticas.",
    "neptune_gemini": "A mente navega entre imaginação, símbolos e múltiplas narrativas. A comunicação torna-se veículo de inspiração ou confusão perceptiva.",
    "neptune_cancer": "A sensibilidade emocional dissolve fronteiras entre memória, imaginação e afeto. O sentimento de lar busca refúgio em vínculos profundamente empáticos.",
    "neptune_leo": "A criatividade expressa imagens simbólicas que evocam sonho e encantamento. O brilho pessoal pode tornar-se veículo de inspiração coletiva.",
    "neptune_virgo": "A busca por ordem encontra o desafio de lidar com ambiguidades e sutilezas. O serviço se torna expressão de compaixão quando a lógica se abre ao sensível.",
    "neptune_libra": "As relações carregam idealizações que buscam harmonia e beleza transcendente. O encontro com o outro torna-se espaço de projeções e sonhos afetivos.",
    "neptune_scorpio": "A psique mergulha em mistérios profundos onde desejo e transcendência se entrelaçam. O inconsciente revela forças simbólicas que dissolvem antigas identidades.",
    "neptune_sagittarius": "A espiritualidade e a filosofia se expandem em busca de sentido universal. A visão de mundo torna-se permeada por mitos, símbolos e narrativas inspiradoras.",
    "neptune_capricorn": "Estruturas de poder e autoridade tornam-se campos de idealização ou desilusão. O senso de realidade é desafiado a integrar responsabilidade e imaginação.",
    "neptune_aquarius": "A utopia coletiva inspira visões de sociedades mais conectadas e livres. Ideais humanitários dissolvem limites entre indivíduos e comunidades.",
    "neptune_pisces": "A sensibilidade se dissolve no oceano simbólico da imaginação e da espiritualidade. A compaixão surge como experiência de unidade com o todo.",

    # PLUTÃO
    "pluto_aries": "A identidade passa por processos intensos de morte e renascimento psicológico. A força de agir emerge transformada após confrontos com o próprio poder.",
    "pluto_taurus": "Valores e recursos tornam-se campos de transformação profunda. O apego ao que é seguro é confrontado para revelar novas formas de poder material.",
    "pluto_gemini": "O pensamento atravessa crises que transformam a maneira de perceber e comunicar. A mente descobre que ideias possuem força capaz de remodelar realidades.",
    "pluto_cancer": "As raízes emocionais passam por processos intensos de purificação e renascimento. O sentimento de pertencimento emerge transformado após confrontos com o passado.",
    "pluto_leo": "A criatividade torna-se palco de intensas transformações do ego. O poder de expressão surge renovado após enfrentar sombras da necessidade de reconhecimento.",
    "pluto_virgo": "O cotidiano revela processos profundos de purificação e reorganização. O controle cede espaço a transformações que redefinem saúde, trabalho e eficiência.",
    "pluto_libra": "Os relacionamentos tornam-se catalisadores de transformações psicológicas profundas. O encontro com o outro revela jogos de poder e necessidade de equilíbrio.",
    "pluto_scorpio": "A psique mergulha em territórios extremos de desejo, poder e regeneração. A transformação emerge através da coragem de atravessar as próprias sombras.",
    "pluto_sagittarius": "Crenças e visões de mundo passam por rupturas que expandem a consciência. A verdade é buscada através de confrontos intensos com dogmas e paradigmas.",
    "pluto_capricorn": "Estruturas de poder, autoridade e ambição passam por profundas metamorfoses. O controle externo se transforma em responsabilidade madura sobre o próprio destino.",
    "pluto_aquarius": "Transformações coletivas emergem através de revoluções sociais e tecnológicas. O poder circula em redes que redefinem liberdade e organização humana.",
    "pluto_pisces": "A dissolução de antigas identidades abre caminho para regenerações espirituais. O inconsciente coletivo revela forças simbólicas que transformam a percepção da realidade.",
}
