SYNASTRY_INTERPRETATIONS = {
    "sun_conjunction_sun": "Há um reconhecimento imediato de identidade e propósito entre vocês. A sensação é de caminhar na mesma direção, com valores e expressões de vida que naturalmente se reforçam.",
    "sun_trine_moon": "A identidade de um encontra acolhimento no mundo emocional do outro. Existe uma fluidez natural entre quem um é e como o outro sente, favorecendo cumplicidade e apoio mútuo.",
    "sun_square_moon": "O modo de ser de um pode ativar reações emocionais intensas no outro. Essa tensão cria atração e crescimento, mas exige aprendizado para integrar vontade e sensibilidade.",
    "sun_opposition_moon": "Há uma dinâmica de complementaridade que pode gerar forte atração. A identidade de um espelha necessidades emocionais profundas do outro, pedindo equilíbrio entre individualidade e vínculo.",
    "sun_conjunction_moon": "A presença de um toca diretamente o mundo emocional do outro. Há sensação de familiaridade e pertencimento, como se a identidade de um fosse naturalmente acolhida pelo coração do outro.",
    "sun_conjunction_venus": "Um ilumina o senso de afeto, beleza e prazer do outro. A relação tende a despertar admiração, carinho e um desejo espontâneo de agradar e valorizar o parceiro.",
    "sun_trine_venus": "Existe facilidade em expressar afeto e apreciação entre vocês. O modo de ser de um naturalmente ativa o amor, a gentileza e o prazer no outro.",
    "sun_square_venus": "A atração é forte, mas pode haver desencontro entre identidade e expectativas afetivas. Um pode sentir que precisa ajustar seu jeito de ser para corresponder ao que o outro valoriza.",
    "moon_conjunction_moon": "As emoções de vocês vibram em sintonia. Existe um entendimento instintivo sobre necessidades emocionais, criando sensação de intimidade e segurança.",
    "moon_trine_moon": "Há harmonia natural entre as formas de sentir e reagir emocionalmente. O convívio tende a ser acolhedor, com empatia espontânea e suporte mútuo.",
    "moon_square_moon": "Os ritmos emocionais podem ser diferentes, gerando reações intensas entre vocês. Essa dinâmica desafia o casal a desenvolver escuta e adaptação afetiva.",
    "moon_conjunction_venus": "O afeto flui com ternura e sensibilidade. Um desperta no outro o desejo de cuidar, acolher e expressar carinho de forma muito natural.",
    "moon_trine_venus": "Há suavidade e conforto emocional na forma como vocês se relacionam. O amor tende a se expressar com gentileza, criando um clima afetivo agradável.",
    "moon_square_venus": "As necessidades emocionais podem nem sempre coincidir com a forma como o outro expressa amor. Isso cria momentos de frustração afetiva, mas também oportunidade de aprender sobre as linguagens do afeto.",
    "moon_conjunction_mars": "As emoções despertam ação imediata entre vocês. Há intensidade emocional e reatividade, podendo gerar tanto paixão quanto conflitos rápidos.",
    "venus_conjunction_mars": "A atração física e magnética é evidente. O encontro entre desejo e afeto cria forte química e impulso de aproximação.",
    "venus_trine_mars": "Existe equilíbrio entre paixão e carinho. O desejo se expressa de forma natural e harmoniosa, fortalecendo tanto o erotismo quanto o vínculo afetivo.",
    "venus_square_mars": "A química é intensa, mas pode vir acompanhada de tensão. A relação mistura atração e frustração, estimulando jogos de aproximação e afastamento.",
    "venus_opposition_mars": "A polaridade entre desejo e afeto cria grande magnetismo. Um desperta no outro um forte impulso relacional, mas também desafios para equilibrar iniciativa e receptividade.",
    "venus_sextile_mars": "A atração se constrói com leveza e cumplicidade. Existe facilidade em combinar carinho e desejo de forma espontânea.",
    "mercury_conjunction_mercury": "As mentes se reconhecem rapidamente. A comunicação flui com naturalidade, criando troca intelectual e facilidade de entendimento.",
    "mercury_trine_mercury": "Há harmonia na forma de pensar e comunicar. Conversas tendem a ser produtivas, estimulantes e construtivas para o vínculo.",
    "mercury_square_mercury": "Diferenças na forma de pensar podem gerar debates frequentes. Essa tensão mental pode ser desafiadora, mas também muito estimulante.",
    "saturn_conjunction_sun": "A relação traz um senso forte de compromisso e responsabilidade. Um pode atuar como estrutura ou guia para o outro, criando um vínculo sério e significativo.",
    "saturn_trine_sun": "Existe apoio sólido para o crescimento pessoal dentro da relação. O parceiro tende a incentivar maturidade e estabilidade na expressão da identidade.",
    "saturn_square_sun": "Um pode sentir que o outro impõe limites ou cobranças à sua expressão pessoal. Essa dinâmica exige maturidade para transformar pressão em construção conjunta.",
    "saturn_conjunction_moon": "A relação desperta emoções profundas ligadas a segurança e vulnerabilidade. Pode haver sensação de proteção, mas também de peso emocional ou responsabilidade.",
    "saturn_square_moon": "As emoções podem encontrar resistência ou rigidez no vínculo. Essa tensão pede paciência para que o cuidado emocional não seja percebido como distância.",
    "saturn_trine_moon": "Há estabilidade emocional no vínculo. Um oferece ao outro sensação de segurança, maturidade e sustentação afetiva.",
    "saturn_conjunction_venus": "O amor ganha um tom de compromisso e seriedade. A relação pode se construir lentamente, mas com grande potencial de durabilidade.",
    "saturn_square_venus": "Podem surgir medos, inseguranças ou bloqueios na expressão do afeto. A relação convida ambos a amadurecer na forma de amar.",
    "pluto_conjunction_sun": "A presença de um provoca transformações profundas no outro. A relação tem intensidade e poder de alterar identidades e caminhos de vida.",
    "pluto_square_sun": "O vínculo pode ativar dinâmicas de poder e confrontos de vontade. Ao mesmo tempo, existe potencial para profundas transformações pessoais.",
    "pluto_trine_sun": "A relação favorece crescimento e regeneração pessoal. Um estimula no outro coragem para acessar potenciais profundos.",
    "pluto_conjunction_moon": "As emoções se tornam extremamente intensas e transformadoras. O vínculo pode tocar camadas psíquicas profundas, gerando forte conexão.",
    "pluto_square_moon": "A relação pode despertar emoções intensas, ciúmes ou dinâmicas inconscientes. O desafio é transformar intensidade em consciência emocional.",
    "pluto_conjunction_venus": "O amor adquire uma qualidade magnética e profunda. A atração pode ser quase irresistível, marcada por intensidade emocional e desejo de fusão.",
    "pluto_square_venus": "A relação mistura paixão, fascínio e possíveis jogos de poder. O vínculo desafia ambos a lidar com apego, controle e intensidade afetiva.",
    "mars_conjunction_mars": "A energia de ação de vocês se encontra diretamente. Isso pode gerar grande dinamismo e entusiasmo conjunto, mas também competitividade.",
    "mars_square_mars": "As vontades podem colidir facilmente. A relação tem forte energia, mas exige aprendizado para transformar confronto em cooperação.",
    "mars_square_saturn": "Marte em quadratura com Saturno em sinastria pode gerar atrito entre ritmo e controle. Um pode sentir que o outro freia sua energia, enquanto o outro sente impulsividade excessiva.",
    "jupiter_conjunction_sun": "Um amplia o senso de propósito e confiança do outro. A relação tende a trazer entusiasmo, crescimento e apoio mútuo.",
    "jupiter_trine_sun": "Existe incentivo natural para expansão e realização pessoal. O vínculo desperta otimismo e sensação de possibilidades.",
    "jupiter_conjunction_moon": "O parceiro tende a ampliar o mundo emocional do outro com generosidade e acolhimento. Há sensação de proteção, alegria e crescimento emocional no vínculo.",
    "sun_in_7th": "Quando o Sol do outro ativa sua Casa 7, a relação ganha foco de parceria e espelhamento. Há um convite para desenvolver autoconhecimento através do encontro com o outro.",
}
